
import React, { useState, useEffect } from 'react';
import { AnalysisRecord } from '../types';
import { Icons } from '../constants';

interface HistoryPageProps {
  searchTerm: string;
}

const HistoryPage: React.FC<HistoryPageProps> = ({ searchTerm }) => {
  const [history, setHistory] = useState<AnalysisRecord[]>([]);

  useEffect(() => {
    // Seed initial history if none exists
    const storedHistory = localStorage.getItem('pharmaGuardHistory');
    if (!storedHistory) {
      const initialHistory: AnalysisRecord[] = [
        { id: 'ANL-92381', date: '2024-05-20T10:30:00Z', patientId: 'PX-1029', drugs: ['CLOPIDOGREL', 'WARFARIN'], status: 'Complete' },
        { id: 'ANL-92382', date: '2024-05-21T14:45:00Z', patientId: 'PX-2041', drugs: ['SIMVASTATIN'], status: 'Complete' },
        { id: 'ANL-92383', date: '2024-05-21T16:20:00Z', patientId: 'PX-9921', drugs: ['CODEINE', 'AMITRIPTYLINE'], status: 'Pending' },
        { id: 'ANL-92384', date: '2024-05-18T09:15:00Z', patientId: 'PX-5501', drugs: ['TAMOXIFEN'], status: 'Complete' },
      ];
      localStorage.setItem('pharmaGuardHistory', JSON.stringify(initialHistory));
      setHistory(initialHistory);
    } else {
      setHistory(JSON.parse(storedHistory));
    }
  }, []);

  const filteredHistory = history.filter(record => 
    record.id.toLowerCase().includes(searchTerm.toLowerCase()) ||
    record.patientId.toLowerCase().includes(searchTerm.toLowerCase()) ||
    record.drugs.some(d => d.toLowerCase().includes(searchTerm.toLowerCase()))
  );

  return (
    <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="mb-8 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Reports History</h1>
          <p className="text-slate-500">Access and audit all clinical pharmacogenomic reports generated by the system.</p>
        </div>
        <div className="flex gap-2">
          {searchTerm && (
            <div className="flex items-center gap-2 px-3 py-1.5 bg-sky-50 text-sky-700 text-xs font-bold rounded-lg border border-sky-100">
              Results for: {searchTerm}
            </div>
          )}
          <button className="px-4 py-2 bg-white border border-slate-200 rounded-lg text-sm font-semibold text-slate-600 hover:bg-slate-50 transition-colors">Filter</button>
          <button className="px-4 py-2 bg-white border border-slate-200 rounded-lg text-sm font-semibold text-slate-600 hover:bg-slate-50 transition-colors">Sort</button>
        </div>
      </div>

      <div className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left">
            <thead>
              <tr className="bg-slate-50 text-slate-500 text-[11px] uppercase tracking-wider font-bold">
                <th className="px-8 py-5">Date</th>
                <th className="px-8 py-5">Report ID</th>
                <th className="px-8 py-5">Patient ID</th>
                <th className="px-8 py-5">Screened Drugs</th>
                <th className="px-8 py-5">Outcome Status</th>
                <th className="px-8 py-5"></th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filteredHistory.length > 0 ? filteredHistory.map((report) => (
                <tr key={report.id} className="hover:bg-slate-50 transition-colors group">
                  <td className="px-8 py-5 text-sm text-slate-500">{new Date(report.date).toLocaleDateString()}</td>
                  <td className="px-8 py-5 font-mono text-xs font-bold text-sky-700">{report.id}</td>
                  <td className="px-8 py-5 font-semibold text-slate-800">{report.patientId}</td>
                  <td className="px-8 py-5">
                    <div className="flex flex-wrap gap-1">
                      {report.drugs.map((d, i) => (
                        <span key={i} className="px-2 py-0.5 bg-slate-100 text-slate-600 rounded text-[10px] font-bold uppercase border border-slate-200">{d}</span>
                      ))}
                    </div>
                  </td>
                  <td className="px-8 py-5">
                    <span className={`px-2.5 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider ${
                      report.status === 'Complete' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'
                    }`}>
                      {report.status}
                    </span>
                  </td>
                  <td className="px-8 py-5 text-right">
                    <button className="text-slate-400 hover:text-sky-600 p-2 rounded-lg hover:bg-sky-50 transition-colors opacity-0 group-hover:opacity-100">
                      <Icons.History className="w-4 h-4" />
                    </button>
                  </td>
                </tr>
              )) : (
                <tr>
                  <td colSpan={6} className="px-8 py-16 text-center text-slate-400 italic">No historical reports match your search criteria.</td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
        
        <div className="p-6 bg-slate-50 border-t border-slate-100 flex items-center justify-between text-sm text-slate-500">
          <p>Showing {filteredHistory.length} reports</p>
          <div className="flex gap-2">
            <button className="px-3 py-1 bg-white border border-slate-200 rounded-md disabled:opacity-50" disabled>Previous</button>
            <button className="px-3 py-1 bg-white border border-slate-200 rounded-md disabled:opacity-50" disabled>Next</button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default HistoryPage;
